<?php

namespace AppBundle\Repository;

/**
 * CasoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CasoRepository extends \Doctrine\ORM\EntityRepository
{
    public function filtroDQL($codigoClientePk = 0) {
        $dql   = "SELECT d, e FROM BrasaRecursoHumanoBundle:RhuDotacion d JOIN d.empleadoRel e WHERE d.codigoDotacionPk <> 0";

        $dql .= " ORDER BY d.codigoDotacionPk DESC";
        return $dql;
    }
}