<?php

namespace AppBundle\Repository;

/**
 * NoContestanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoContestanRepository extends \Doctrine\ORM\EntityRepository
{
}
