<?php

namespace AppBundle\Repository;

/**
 * TareaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TareaRepository extends \Doctrine\ORM\EntityRepository
{


    public function listaDql()
    {
        $em = $this->getEntityManager();
        $db = $em->createQueryBuilder()->from("AppBundle:Tarea", "t")
            ->select("t")
            ->where("t.codigoTareaPk <> 0")
            ->orderBy("t.estadoTerminado", "ASC")
        ->getQuery();

        return $db->getResult();

    }

}
