# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    encoders:
        AppBundle\Entity\Usuario:
                    algorithm: bcrypt

#            Symfony\Component\Security\Core\User\User:
#                algorithm: bcrypt




    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:

          database_users:
              entity:
                  class: AppBundle:Usuario
                  property: codigoUsuarioPk
#        in_memory:
#            memory:
#                users:
#                    admin:
#                        password: $2y$13$ot7BsQh7TNO3nemYhTefV.pGjnevUttJ7vHtFHOpQOzErC4nu2y/a
#                        roles: 'ROLE_ADMIN'

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            provider: database_users
            form_login:
                login_path: acceso
                check_path: acceso
            logout: true

            http_basic: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
